logo: "/images/my headshot round.png?raw=true" # your photo (or logo) here
#<br><br>
title: <center>Evan Almaas </center> # (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
  Evan has helped organizations grow, analyze and visualize data, develop and launch products, and manage risk for 12 years. 
  He has worked at Capital One and Starbucks and for several Fortune 500 companies as a strategy consultant with Accenture.
  <br><br>
  He earned his MBA from Darden at the University of Virginia (ranked #3 in the US by <a href="https://www.bloomberg.com/business-schools/regions/us/">Bloomberg</a>). 
  <br>
  <!--Evan currently resides with his family near Cambridge in the United Kingdom. He enjoys exploring the UK and Europe, running with his dog, hiking, reading, cooking and chasing his young children.-->
  </p>
  
  <a href="mailto:evan.almaas@gmail.com">Email me</a> or visit my <a href="https://www.linkedin.com/in/evanalmaas/">LinkedIn page</a> to find out more.
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
