logo: "/images/my headshot round.png?raw=true" # your photo (or logo) here
title: Evan Almaas # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an awesome person making this website. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/evanalmaas/">View My LinkedIn Profile</a>
  <a href="evan.almaas@gmail.com">Email Me</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
