title: Evan Almaas # your name (or website title) here
logo: "/images/my headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an awesome person making this website. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/evanalmaas/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
