logo: "/images/my headshot round.png?raw=true" # your photo (or logo) here
#<br><br>
title: <center>Evan Almaas </center> # (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Evan Almaas has helped organizations grow, analyze and visualize data, and manage risk for 12 years. His experience spans product strategy, analytics, data modeling, mobile user experience, marketing, risk management, and management consulting. He has worked at Capital One and Starbucks and for several Fortune 500 companies as a strategy consultant with Accenture. He also served in the U.S. Marine Corps.
  <br><br>
  He earned his Master in Business Administration (MBA) with top honors from the Darden School of Business at the University of Virginia (ranked #3 in the US by Bloomberg). 
  <br><br>
  Evan currently resides with his family near Cambridge in the United Kingdom. He enjoys exploring the UK and Europe, running with his dog, hiking, reading, cooking and chasing his young children.
  <br><br>
  <a href="https://www.linkedin.com/in/evanalmaas/">View My LinkedIn Profile</a>
  <br><br>
  <a href="mailto:evan.almaas@gmail.com">Email Me</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
